// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-QTQEBSYa_t_-uCmk17HSN_w8TDbdvo',
    appId: '1:244094132223:web:db2c6d5e90a4eda64a51ca',
    messagingSenderId: '244094132223',
    projectId: 'ai-investment-app-2026',
    authDomain: 'ai-investment-app-2026.firebaseapp.com',
    storageBucket: 'ai-investment-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqB_cav-pENjxZ1Yjwnk64akcX15vv6o',
    appId: '1:244094132223:android:7933abefc3f4b7e64a51ca',
    messagingSenderId: '244094132223',
    projectId: 'ai-investment-app-2026',
    storageBucket: 'ai-investment-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-7OvnvovcQQx6ri6LODnsYz0_XJI39o',
    appId: '1:244094132223:ios:f1d1fdbb78ce8ecf4a51ca',
    messagingSenderId: '244094132223',
    projectId: 'ai-investment-app-2026',
    storageBucket: 'ai-investment-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.aiInvestmentApp',
  );
}
